language: python
python:
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: woodpecker324
  password:
    secure: ndJj4aaNyMgaBFdXXDgSHr3ZqLVwPf63lqXed1BtNA6t/3VbPByIBuDxNVWfAzd7V9cK4wDP5J5CFeWmosof4AokStGWRl+90lX9K7CS57ahyetCCZNOI3euqWil6HR0+bolZL5Prj/4lPsXH8R+DvsWd0tHNlws8P2qgsizOQlFx8k6oacUbObYcZAcdTYU6+0kxqHLVKLOvraHTqQSAlabJe/OlId+WKHispcspvqbOyQHpSuRDebmHjiUKzOSJI4CmqZ8r43wkDzAHMHVK4X0oZPJR/PaC7i0aCHnBPR0uWY4gxBudivYCq0ogf/4NXineNqXwMfekkd5CwFKOPudnmg+SLUGzvBG/lMkrWLsocWlLnRRVnPxzZTBKEc58fEhFylgV1osb2VoGWzkY21o6vewcDGkcOAqwp0iV52fHoFJVLqoV/UlW4gY4g/UWOsFhikGi2aIvBNmj7rJOLQpqOX26MoIX+SoArZwkhTXBSLYkIrt3YHfCBEAAJNzrk0v2v0O3QvXhJcX2LdcJtqLDwd6Kky56jE7DgCXZS1MLYSjGRSNPRwmELNNGW5eNGyTMS2OKdSYljpUUTybhz1T0m+oDkEbhccWM7N4sTi3OWvThohzCR2QDwxYPR+l/JRZDfwTQx+r6LQeNdIgWiZGQcu/Qdm6rDPTTXFW2M0=
  on:
    tags: true
    repo: woodpecker324/wrappedbrowser
    python: 3.7
